function build_simulink_model()
% BUILD_SIMULINK_MODEL  Creates PFD Signal Generator Simulink model
%
% Programmatically builds a Simulink block diagram representing the
% signal generation process from generator.m.
%
% Requirements: MATLAB R2024b with Simulink
%

fprintf('\n========================================\n');
fprintf('  PFD Simulink Model Builder v1.0\n');
fprintf('========================================\n\n');

% Configuration
modelName = 'PFD_Signal_Generator';
fs = 20480;
T  = 5;
Ts = 1/fs;

% Version management
scriptDir = fileparts(mfilename('fullpath'));
buildsDir = fullfile(scriptDir, 'builds');
latestDir = fullfile(scriptDir, 'latest');
if ~exist(buildsDir, 'dir'), mkdir(buildsDir); end
if ~exist(latestDir, 'dir'), mkdir(latestDir); end

existing = dir(fullfile(buildsDir, [modelName '_v*.slx']));
version = length(existing) + 1;
timestamp = datestr(now, 'yyyymmdd_HHMM');
buildFile = fullfile(buildsDir, ...
    sprintf('%s_v%d_%s.slx', modelName, version, timestamp));
latestFile = fullfile(latestDir, [modelName '.slx']);

fprintf('Build v%d | %s\n\n', version, timestamp);

% Close if already open
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

% Create model
new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'Solver', 'ode4', ...
    'FixedStep', num2str(Ts), ...
    'StopTime', num2str(T), ...
    'ReturnWorkspaceOutputs', 'off');  % x_sim goes to base workspace

% ---- Top-level subsystem blocks ----
subs = {
    'Operating_Conditions', [50,  30,  230, 90],  [0.6 0.8 1.0]
    'Base_Signal',          [50,  160, 230, 220], [0.7 1.0 0.7]
    'Fault_Injection',      [50,  290, 230, 370], [1.0 0.7 0.7]
    'Severity_Control',     [330, 290, 510, 350], [0.9 0.7 1.0]
    'Transient_Behavior',   [600, 290, 780, 350], [1.0 0.9 0.7]
    'Noise_Model',          [50,  440, 230, 520], [1.0 0.85 0.6]
};

for i = 1:size(subs,1)
    blk = [modelName '/' subs{i,1}];
    add_block('simulink/Ports & Subsystems/Subsystem', blk, ...
        'Position', subs{i,2});
    set_param(blk, 'BackgroundColor', ...
        sprintf('[%g, %g, %g]', subs{i,3}));
end

% ---- Output blocks ----
add_block('simulink/Math Operations/Sum', ...
    [modelName '/Signal_Sum'], ...
    'Inputs', '+++', ...
    'Position', [880, 280, 920, 340]);

add_block('simulink/Sinks/Scope', ...
    [modelName '/Scope'], ...
    'Position', [1020, 270, 1080, 310]);

add_block('simulink/Sinks/To Workspace', ...
    [modelName '/To_Workspace'], ...
    'Position', [1020, 330, 1100, 360], ...
    'VariableName', 'x_sim', ...
    'SaveFormat', 'Array');

% Wire Sum to outputs
add_line(modelName, 'Signal_Sum/1', 'Scope/1', ...
    'autorouting', 'smart');
add_line(modelName, 'Signal_Sum/1', 'To_Workspace/1', ...
    'autorouting', 'smart');

% ---- Build subsystem internals ----
fprintf('Step 2: Operating_Conditions\n');
build_operating_conditions(modelName);

fprintf('Step 3: Base_Signal\n');
build_base_signal(modelName, Ts);

fprintf('Step 4: Noise_Model\n');
build_noise_model(modelName, Ts, fs);

fprintf('Step 5-6: Fault_Injection\n');
build_fault_injection(modelName, Ts, fs);

fprintf('Step 7: Severity_Control\n');
build_severity_control(modelName, Ts);

fprintf('Step 8: Transient_Behavior\n');
build_transient_behavior(modelName, Ts);

fprintf('Step 10: Top-level wiring\n');
wire_top_level(modelName);

% ---- Save ----
save_system(modelName, buildFile);
copyfile(buildFile, latestFile);
close_system(modelName);

fprintf('\n========================================\n');
fprintf('  BUILD COMPLETE - v%d\n', version);
fprintf('  %s\n', buildFile);
fprintf('========================================\n\n');
end

%% --- Subsystem builders (each added incrementally) ---

function build_operating_conditions(modelName)
    sys = [modelName '/Operating_Conditions'];

    % Remove default blocks
    delete_default_ports(sys);

    % --- Tunable Constants ---
    add_block('simulink/Sources/Constant', [sys '/Speed_RPM'], ...
        'Value', '3600', 'Position', [30, 25, 130, 45]);
    add_block('simulink/Sources/Constant', [sys '/Load_Percent'], ...
        'Value', '70', 'Position', [30, 75, 130, 95]);
    add_block('simulink/Sources/Constant', [sys '/Temperature_C'], ...
        'Value', '60', 'Position', [30, 125, 130, 145]);

    % --- Omega: RPM→Hz→rad/s ---
    add_block('simulink/Math Operations/Gain', [sys '/RPM_to_Hz'], ...
        'Gain', '1/60', 'Position', [180, 25, 230, 45]);
    add_block('simulink/Math Operations/Gain', [sys '/Hz_to_rads'], ...
        'Gain', '2*pi', 'Position', [280, 25, 330, 45]);
    add_line(sys, 'Speed_RPM/1', 'RPM_to_Hz/1');
    add_line(sys, 'RPM_to_Hz/1', 'Hz_to_rads/1');
    add_goto_block(sys, 'g_omega', 'omega', [380, 25, 440, 45], 'Hz_to_rads/1');
    add_goto_block(sys, 'g_Omega_Hz', 'Omega_Hz', [380, 60, 450, 80], 'RPM_to_Hz/1');

    % --- Load factor: 0.3 + 0.7*(Load/100) ---
    add_block('simulink/Math Operations/Gain', [sys '/Load_Norm'], ...
        'Gain', '0.7/100', 'Position', [180, 75, 240, 95]);
    add_block('simulink/Sources/Constant', [sys '/Bias_03'], ...
        'Value', '0.3', 'Position', [180, 105, 230, 120]);
    add_block('simulink/Math Operations/Add', [sys '/Load_Sum'], ...
        'Inputs', '++', 'Position', [290, 80, 320, 110]);
    add_line(sys, 'Load_Percent/1', 'Load_Norm/1');
    add_line(sys, 'Load_Norm/1', 'Load_Sum/1');
    add_line(sys, 'Bias_03/1', 'Load_Sum/2');
    add_goto_block(sys, 'g_lf', 'load_factor', [370, 85, 450, 105], 'Load_Sum/1');

    % --- Temp factor: 0.9 + 0.2*((T-40)/40) ---
    add_block('simulink/Sources/Constant', [sys '/Ref_40'], ...
        'Value', '40', 'Position', [110, 155, 150, 170]);
    add_block('simulink/Math Operations/Add', [sys '/T_Sub'], ...
        'Inputs', '+-', 'Position', [180, 130, 210, 160]);
    add_block('simulink/Math Operations/Gain', [sys '/T_Scale'], ...
        'Gain', '0.2/40', 'Position', [240, 130, 300, 150]);
    add_block('simulink/Sources/Constant', [sys '/Bias_09'], ...
        'Value', '0.9', 'Position', [240, 165, 290, 180]);
    add_block('simulink/Math Operations/Add', [sys '/T_Add'], ...
        'Inputs', '++', 'Position', [340, 135, 370, 165]);
    add_line(sys, 'Temperature_C/1', 'T_Sub/1');
    add_line(sys, 'Ref_40/1', 'T_Sub/2');
    add_line(sys, 'T_Sub/1', 'T_Scale/1');
    add_line(sys, 'T_Scale/1', 'T_Add/1');
    add_line(sys, 'Bias_09/1', 'T_Add/2');
    add_goto_block(sys, 'g_tf', 'temp_factor', [410, 140, 500, 160], 'T_Add/1');

    % --- operating_factor = load_factor * temp_factor ---
    add_block('simulink/Math Operations/Product', [sys '/Op_Prod'], ...
        'Position', [290, 200, 320, 230]);
    add_from_block(sys, 'f_lf', 'load_factor', [180, 200, 260, 215]);
    add_from_block(sys, 'f_tf', 'temp_factor', [180, 225, 260, 240]);
    add_line(sys, 'f_lf/1', 'Op_Prod/1');
    add_line(sys, 'f_tf/1', 'Op_Prod/2');
    add_goto_block(sys, 'g_of', 'operating_factor', [360, 205, 470, 225], 'Op_Prod/1');

    % --- amp_base = 0.25 * operating_factor ---
    add_block('simulink/Math Operations/Gain', [sys '/Amp_Gain'], ...
        'Gain', '0.25', 'Position', [360, 240, 410, 260]);
    add_from_block(sys, 'f_of2', 'operating_factor', [260, 240, 350, 255]);
    add_line(sys, 'f_of2/1', 'Amp_Gain/1');
    add_goto_block(sys, 'g_ab', 'amp_base', [450, 240, 530, 260], 'Amp_Gain/1');

    % --- Sommerfeld (MATLAB Function) ---
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [sys '/Sommerfeld_Calc'], 'Position', [180, 280, 330, 320]);

    % Set code FIRST so ports are created (3 inputs, 3 outputs)
    set_sommerfeld_code(sys);

    % Wire Sommerfeld inputs
    add_line(sys, 'Temperature_C/1', 'Sommerfeld_Calc/1', 'autorouting','smart');
    add_from_block(sys, 'f_oh', 'Omega_Hz', [80, 300, 160, 315]);
    add_line(sys, 'f_oh/1', 'Sommerfeld_Calc/2', 'autorouting', 'smart');
    add_from_block(sys, 'f_lf2', 'load_factor', [80, 320, 160, 335]);
    add_line(sys, 'f_lf2/1', 'Sommerfeld_Calc/3', 'autorouting', 'smart');

    % Wire Sommerfeld outputs to Goto
    add_goto_block(sys, 'g_somm', 'sommerfeld', [380, 275, 470, 295], 'Sommerfeld_Calc/1');
    add_goto_block(sys, 'g_pf', 'physics_factor', [380, 300, 480, 320], 'Sommerfeld_Calc/2');
    add_goto_block(sys, 'g_sv', 'speed_variation', [380, 325, 490, 345], 'Sommerfeld_Calc/3');

    % --- Dummy outport (subsystem needs at least one output) ---
    add_block('simulink/Ports & Subsystems/Out1', [sys '/params_out'], ...
        'Position', [550, 25, 580, 45]);
    add_from_block(sys, 'f_omega_out', 'omega', [490, 25, 540, 45]);
    add_line(sys, 'f_omega_out/1', 'params_out/1');
end

function set_sommerfeld_code(sys)
    try
        sf_root = sfroot;
        chart = sf_root.find('-isa', 'Stateflow.EMChart', ...
            'Path', [sys '/Sommerfeld_Calc']);
        if ~isempty(chart)
            chart.Script = [...
                'function [sommerfeld, physics_factor, speed_var] = ' ...
                'Sommerfeld_Calc(T_C, Omega_Hz, lf)' newline ...
                '% Sommerfeld number from operating conditions' newline ...
                '% Based on generator.m physics' newline ...
                'S_base = 0.15;' newline ...
                'visc = exp(-0.03 * (T_C - 60));' newline ...
                'spd = Omega_Hz / 60;' newline ...
                'lf_inv = 1.0 / lf;' newline ...
                'sommerfeld = S_base * visc * spd * lf_inv;' newline ...
                'sommerfeld = max(0.05, min(0.5, sommerfeld));' newline ...
                'physics_factor = sqrt(sommerfeld / S_base);' newline ...
                'speed_var = Omega_Hz / 60;  % speed ratio (C1 fix)' newline];
        end
    catch ME
        fprintf('  Warning: Could not set Sommerfeld code: %s\n', ME.message);
    end
end

function build_base_signal(modelName, Ts)
    sys = [modelName '/Base_Signal'];
    delete_default_ports(sys);

    % White noise source (baseline vibration)
    % Band-Limited White Noise: output variance = Cov/Ts
    % To get std=1 output (like randn), set Cov = Ts
    add_block('simulink/Sources/Band-Limited White Noise', ...
        [sys '/White_Noise'], ...
        'Cov', num2str(Ts), 'Ts', num2str(Ts), ...
        'Position', [30, 30, 100, 60]);

    % Scale by amp_base * 0.05
    add_from_block(sys, 'f_amp', 'amp_base', [30, 80, 110, 95]);
    add_block('simulink/Math Operations/Gain', [sys '/Scale_005'], ...
        'Gain', '0.05', 'Position', [140, 80, 190, 100]);
    add_line(sys, 'f_amp/1', 'Scale_005/1');

    % Multiply noise by scaled amplitude
    add_block('simulink/Math Operations/Product', [sys '/Noise_Scale'], ...
        'Position', [230, 40, 260, 75]);
    add_line(sys, 'White_Noise/1', 'Noise_Scale/1');
    add_line(sys, 'Scale_005/1', 'Noise_Scale/2');

    % Output
    add_block('simulink/Ports & Subsystems/Out1', [sys '/base_out'], ...
        'Position', [310, 50, 340, 65]);
    add_line(sys, 'Noise_Scale/1', 'base_out/1');
end

function build_noise_model(modelName, Ts, fs)
    sys = [modelName '/Noise_Model'];
    delete_default_ports(sys);

    y = 30; % vertical offset tracker
    sp = 55; % spacing

    % 1. Measurement noise (Gaussian, sigma=0.03)
    %    Band-Limited White Noise: output variance = Cov/Ts
    %    To get std=0.03, set Cov = 0.03^2 * Ts
    add_block('simulink/Sources/Band-Limited White Noise', ...
        [sys '/Measurement_Noise'], ...
        'Cov', num2str(0.03^2 * Ts), 'Ts', num2str(Ts), ...
        'Position', [30, y, 130, y+25]);

    % 2. EMI (50 Hz sine, amp=0.01)
    y = y + sp;
    add_block('simulink/Sources/Sine Wave', [sys '/EMI_50Hz'], ...
        'Amplitude', '0.01', 'Frequency', '2*pi*50', ...
        'SampleTime', num2str(Ts), ...
        'Position', [30, y, 130, y+25]);

    % 3. Pink noise (cumsum approximation via Integrator + white noise)
    %    C3 fix: Scale Cov down so integrated output stays bounded (~0.02 std)
    y = y + sp;
    add_block('simulink/Sources/Band-Limited White Noise', ...
        [sys '/Pink_Source'], ...
        'Cov', num2str(0.0001 * Ts), 'Ts', num2str(Ts), ...
        'Position', [30, y, 100, y+25]);
    add_block('simulink/Discrete/Discrete-Time Integrator', ...
        [sys '/Pink_Integrator'], ...
        'SampleTime', num2str(Ts), ...
        'InitialCondition', '0', ...
        'UpperSaturationLimit', '0.05', ...
        'LowerSaturationLimit', '-0.05', ...
        'LimitOutput', 'on', ...
        'Position', [130, y, 190, y+25]);
    add_block('simulink/Math Operations/Gain', [sys '/Pink_Gain'], ...
        'Gain', '1.0', 'Position', [220, y, 270, y+25]);
    add_line(sys, 'Pink_Source/1', 'Pink_Integrator/1');
    add_line(sys, 'Pink_Integrator/1', 'Pink_Gain/1');

    % 4. Drift (slow sine at 0.667 Hz)
    y = y + sp;
    add_block('simulink/Sources/Sine Wave', [sys '/Drift'], ...
        'Amplitude', '0.015', 'Frequency', '2*pi/1.5', ...
        'SampleTime', num2str(Ts), ...
        'Position', [30, y, 130, y+25]);

    % 5. Quantization (step = 0.001)
    % Applied differently: passes through the signal, so we skip
    % adding it to the sum. Instead we'll apply it post-sum.
    % Place a Quantizer in the top level. For now add a zero placeholder.
    y = y + sp;
    add_block('simulink/Sources/Constant', [sys '/Quant_Zero'], ...
        'Value', '0', 'Position', [30, y, 100, y+20]);

    % 6. Sensor drift (linear ramp: sensor_drift_rate * t)
    %    generator.m: rate=0.001, offset = rate/T * t
    y = y + sp;
    add_block('simulink/Sources/Ramp', [sys '/Sensor_Drift_Ramp'], ...
        'Slope', num2str(0.001/5), ...  % 0.001 drift over 5s
        'Position', [30, y, 130, y+25]);

    % 7. Impulse noise (Pulse Generator, rate=2/sec)
    y = y + sp;
    add_block('simulink/Sources/Pulse Generator', [sys '/Impulse_Pulse'], ...
        'PulseType', 'Sample based', ...
        'Amplitude', '0.03', ...
        'Period', num2str(round(0.5*fs)), ...  % 0.5s in samples
        'PulseWidth', '5', ...
        'PhaseDelay', '0', ...
        'SampleTime', num2str(Ts), ...
        'Position', [30, y, 130, y+25]);

    % 8. Aliasing (near-Nyquist sine)
    y = y + sp;
    alias_freq = fs/2 + 200;
    add_block('simulink/Sources/Sine Wave', [sys '/Aliasing'], ...
        'Amplitude', '0.005', ...
        'Frequency', sprintf('2*pi*%g', alias_freq), ...
        'SampleTime', num2str(Ts), ...
        'Position', [30, y, 130, y+25]);

    % --- Sum all noise sources (8 inputs) ---
    add_block('simulink/Math Operations/Sum', [sys '/Noise_Sum'], ...
        'Inputs', '++++++++', ...
        'Position', [350, 80, 380, 350]);

    % Wire each source to Sum
    sources = {'Measurement_Noise', 'EMI_50Hz', 'Pink_Gain', ...
               'Drift', 'Quant_Zero', 'Sensor_Drift_Ramp', ...
               'Impulse_Pulse', 'Aliasing'};
    for i = 1:length(sources)
        add_line(sys, [sources{i} '/1'], sprintf('Noise_Sum/%d', i), ...
            'autorouting', 'smart');
    end

    % Output
    add_block('simulink/Ports & Subsystems/Out1', [sys '/noise_out'], ...
        'Position', [430, 205, 460, 225]);
    add_line(sys, 'Noise_Sum/1', 'noise_out/1');
end

function build_fault_injection(modelName, Ts, fs)
    sys = [modelName '/Fault_Injection'];
    delete_default_ports(sys);

    % Fault type selector (1=Healthy ... 11=Mixed_Cavit_Jeu)
    add_block('simulink/Sources/Constant', [sys '/Fault_Type'], ...
        'Value', '2', 'Position', [30, 30, 130, 50]);

    % From blocks for operating parameters
    add_from_block(sys, 'f_omega', 'omega', [30, 70, 110, 85]);
    add_from_block(sys, 'f_Omega', 'Omega_Hz', [30, 95, 120, 110]);
    add_from_block(sys, 'f_somm', 'sommerfeld', [30, 120, 120, 135]);
    add_from_block(sys, 'f_lf', 'load_factor', [30, 145, 120, 160]);
    add_from_block(sys, 'f_tf', 'temp_factor', [30, 170, 120, 185]);
    add_from_block(sys, 'f_sv', 'speed_variation', [30, 195, 130, 210]);
    add_from_block(sys, 'f_of', 'operating_factor', [30, 220, 140, 235]);
    add_from_block(sys, 'f_pf', 'physics_factor', [30, 245, 130, 260]);

    % Digital Clock for time vector (discrete, at Ts — required for randn in MATLAB Function)
    add_block('simulink/Sources/Digital Clock', [sys '/Clock'], ...
        'SampleTime', num2str(1/20480), ...
        'Position', [30, 270, 80, 290]);

    % MATLAB Function: generates fault signal based on type
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [sys '/Fault_Generator'], 'Position', [200, 60, 400, 280]);

    % Set code FIRST so 10 input ports + 1 output port are created
    set_fault_generator_code(sys);

    % Wire inputs to MATLAB Function
    inputs = {'Fault_Type','f_omega','f_Omega','f_somm','f_lf', ...
              'f_tf','f_sv','f_of','f_pf','Clock'};
    for i = 1:length(inputs)
        add_line(sys, [inputs{i} '/1'], sprintf('Fault_Generator/%d',i), ...
            'autorouting', 'smart');
    end

    % Output
    add_block('simulink/Ports & Subsystems/Out1', [sys '/fault_out'], ...
        'Position', [460, 160, 490, 180]);
    add_line(sys, 'Fault_Generator/1', 'fault_out/1');
end

function set_fault_generator_code(sys)
    try
        sf_root = sfroot;
        chart = sf_root.find('-isa','Stateflow.EMChart', ...
            'Path',[sys '/Fault_Generator']);
        if ~isempty(chart)
            chart.Script = get_fault_code();
        end
    catch ME
        fprintf('  Warning: Could not set Fault code: %s\n', ME.message);
    end
end

function code = get_fault_code()
    code = [...
    'function fault_sig = Fault_Generator(fault_type, omega, Omega_Hz, sommerfeld, lf, tf, sv, of, pf, t)' newline ...
    '% FAULT_GENERATOR  Physics-based fault signal injection' newline ...
    '% Fault types: 1=Healthy, 2=Misalignment, 3=Imbalance,' newline ...
    '% 4=Clearance, 5=Lubrication, 6=Cavitation, 7=Wear,' newline ...
    '% 8=OilWhirl, 9=Mixed_MI, 10=Mixed_WL, 11=Mixed_CJ' newline ...
    '%' newline ...
    '% Fixed: C1(speed_var), C4(cavitation), M1(wear noise),' newline ...
    '%        M2(lube contacts), M4(oil whirl modulation)' newline ...
    '' newline ...
    'fault_sig = 0;' newline ...
    'ft = round(fault_type);' newline ...
    '' newline ...
    'if ft == 1' newline ...
    '    % Healthy - no fault signature' newline ...
    '    fault_sig = 0;' newline ...
    '' newline ...
    'elseif ft == 2' newline ...
    '    % Misalignment: 2X + 3X harmonics' newline ...
    '    fault_sig = 0.35*sin(2*omega*t) + 0.20*sin(3*omega*t);' newline ...
    '' newline ...
    'elseif ft == 3' newline ...
    '    % Imbalance: dominant 1X, speed-squared (C1 fix: sv from Sommerfeld)' newline ...
    '    fault_sig = 0.5 * lf * sin(omega*t) * sv^2;' newline ...
    '' newline ...
    'elseif ft == 4' newline ...
    '    % Clearance: sub-sync 0.43X + 1X + 2X' newline ...
    '    sub_f = 0.43 * Omega_Hz;' newline ...
    '    fault_sig = 0.25*tf*sin(2*pi*sub_f*t) + 0.18*sin(omega*t) + 0.10*sin(2*omega*t);' newline ...
    '' newline ...
    'elseif ft == 5' newline ...
    '    % Lubrication: stick-slip + metal contact events (M2 fix)' newline ...
    '    ss_freq = 3.5;' newline ...
    '    fault_sig = 0.30 * tf * (0.3/sommerfeld) * sin(2*pi*ss_freq*t);' newline ...
    '    % Metal contact impacts at fixed positions' newline ...
    '    impact_times = [0.8, 1.6, 2.5, 3.4, 4.2];' newline ...
    '    for ji = 1:5' newline ...
    '        dti = t - impact_times(ji);' newline ...
    '        if dti >= 0 && dti < 0.001' newline ...
    '            fault_sig = fault_sig + 0.4 * exp(-500*dti) * randn;' newline ...
    '        end' newline ...
    '    end' newline ...
    '' newline ...
    'elseif ft == 6' newline ...
    '    % Cavitation: deterministic HF bursts with exp decay (C4 fix)' newline ...
    '    burst_times = [0.5, 1.2, 2.1, 2.8, 3.6, 4.3];' newline ...
    '    burst_freqs = [1800, 2200, 1600, 2400, 2000, 1900];' newline ...
    '    burst_len = 0.008;' newline ...
    '    fault_sig = 0;' newline ...
    '    for bi = 1:6' newline ...
    '        dtb = t - burst_times(bi);' newline ...
    '        if dtb >= 0 && dtb < burst_len' newline ...
    '            fault_sig = fault_sig + 0.5*sin(2*pi*burst_freqs(bi)*dtb)*exp(-100*dtb);' newline ...
    '        end' newline ...
    '    end' newline ...
    '' newline ...
    'elseif ft == 7' newline ...
    '    % Wear: broadband noise + harmonics + AM (M1 fix)' newline ...
    '    wear_mod = 1 + 0.3*sin(2*pi*1.0*t);' newline ...
    '    wear_harm = 0.12*(sin(omega*t) + 0.5*sin(2*omega*t));' newline ...
    '    wear_noise = 0.25 * of * pf * randn;' newline ...
    '    fault_sig = (wear_harm + wear_noise) * wear_mod;' newline ...
    '' newline ...
    'elseif ft == 8' newline ...
    '    % Oil Whirl: sub-sync 0.45X + AM modulation (M4 fix)' newline ...
    '    wf = 0.45 * Omega_Hz;' newline ...
    '    subsync_mod = 1 + 0.2*sin(2*pi*wf*0.5*t);' newline ...
    '    fault_sig = 0.40*(1/sqrt(sommerfeld)) * sin(2*pi*wf*t) * subsync_mod;' newline ...
    '' newline ...
    'elseif ft == 9' newline ...
    '    % Mixed: Misalignment + Imbalance' newline ...
    '    mis = 0.25*sin(2*omega*t) + 0.15*sin(3*omega*t);' newline ...
    '    imb = 0.35*lf*sin(omega*t)*sv^2;' newline ...
    '    fault_sig = mis + imb;' newline ...
    '' newline ...
    'elseif ft == 10' newline ...
    '    % Mixed: Wear + Lubrication (with broadband + contacts)' newline ...
    '    wear_noise = 0.18 * of * pf * randn;' newline ...
    '    wear = 0.08*(sin(omega*t) + 0.5*sin(2*omega*t)) + wear_noise;' newline ...
    '    lube = 0.20*tf*(0.3/sommerfeld)*sin(2*pi*3.5*t);' newline ...
    '    fault_sig = wear + lube;' newline ...
    '    % Metal contact impacts' newline ...
    '    ct = [1.0, 2.5, 4.0];' newline ...
    '    for ci = 1:3' newline ...
    '        dtc = t - ct(ci);' newline ...
    '        if dtc >= 0 && dtc < 0.001' newline ...
    '            fault_sig = fault_sig + 0.3*exp(-500*dtc)*randn;' newline ...
    '        end' newline ...
    '    end' newline ...
    '' newline ...
    'elseif ft == 11' newline ...
    '    % Mixed: Cavitation + Clearance (with exp-decay bursts)' newline ...
    '    burst_times = [0.6, 1.5, 2.4, 3.3, 4.1];' newline ...
    '    burst_freqs = [1900, 2100, 1700, 2300, 2000];' newline ...
    '    cav = 0;' newline ...
    '    for bj = 1:5' newline ...
    '        dtj = t - burst_times(bj);' newline ...
    '        if dtj >= 0 && dtj < 0.008' newline ...
    '            cav = cav + 0.4*sin(2*pi*burst_freqs(bj)*dtj)*exp(-100*dtj);' newline ...
    '        end' newline ...
    '    end' newline ...
    '    clr = 0.22*tf*sin(2*pi*0.43*Omega_Hz*t) + 0.15*sin(omega*t);' newline ...
    '    fault_sig = cav + clr;' newline ...
    '' newline ...
    'end' newline];
end

function build_severity_control(modelName, Ts)
    sys = [modelName '/Severity_Control'];
    delete_default_ports(sys);

    % Input: fault signal
    add_block('simulink/Ports & Subsystems/In1', [sys '/fault_in'], ...
        'Position', [30, 100, 60, 115]);

    % Severity level (0-1)
    add_block('simulink/Sources/Constant', [sys '/Severity_Level'], ...
        'Value', '0.7', 'Position', [30, 30, 140, 50]);

    % Enable evolution (0=static, 1=evolving)
    add_block('simulink/Sources/Constant', [sys '/Enable_Evolution'], ...
        'Value', '0', 'Position', [30, 155, 140, 175]);

    % Static severity path (just the constant)
    % Evolution path: ramp from severity to min(1, severity+0.3)
    add_block('simulink/Sources/Ramp', [sys '/Severity_Ramp'], ...
        'Slope', '0.3/5', ... % 0.3 increase over 5 seconds
        'Position', [180, 30, 240, 50]);

    % Add static severity + ramp
    add_block('simulink/Math Operations/Add', [sys '/Sev_Add'], ...
        'Inputs', '++', 'Position', [280, 25, 310, 55]);
    add_line(sys, 'Severity_Level/1', 'Sev_Add/1');
    add_line(sys, 'Severity_Ramp/1', 'Sev_Add/2');

    % Clamp to [0, 1]
    add_block('simulink/Discontinuities/Saturation', [sys '/Clamp'], ...
        'UpperLimit', '1', 'LowerLimit', '0', ...
        'Position', [340, 30, 390, 55]);
    add_line(sys, 'Sev_Add/1', 'Clamp/1');

    % Switch: 0=static severity, 1=evolving
    add_block('simulink/Signal Routing/Switch', [sys '/Evo_Switch'], ...
        'Criteria', 'u2 > Threshold', 'Threshold', '0.5', ...
        'Position', [280, 85, 320, 135]);
    add_line(sys, 'Clamp/1', 'Evo_Switch/1');       % evolving (top)
    add_line(sys, 'Enable_Evolution/1', 'Evo_Switch/2'); % control
    add_line(sys, 'Severity_Level/1', 'Evo_Switch/3');   % static (bottom)

    % Multiply fault signal by severity
    add_block('simulink/Math Operations/Product', [sys '/Sev_Product'], ...
        'Position', [380, 90, 420, 130]);
    add_line(sys, 'fault_in/1', 'Sev_Product/1');
    add_line(sys, 'Evo_Switch/1', 'Sev_Product/2');

    % Output
    add_block('simulink/Ports & Subsystems/Out1', [sys '/sev_out'], ...
        'Position', [470, 100, 500, 120]);
    add_line(sys, 'Sev_Product/1', 'sev_out/1');
end

function build_transient_behavior(modelName, Ts)
    sys = [modelName '/Transient_Behavior'];
    delete_default_ports(sys);

    % Input: signal from severity stage
    add_block('simulink/Ports & Subsystems/In1', [sys '/sig_in'], ...
        'Position', [30, 140, 60, 155]);

    % Transient type (0=none, 1=speed_ramp, 2=load_step, 3=thermal)
    % 1=none, 2=speed_ramp, 3=load_step, 4=thermal (1-based for Multiport Switch)
    add_block('simulink/Sources/Constant', [sys '/Transient_Type'], ...
        'Value', '1', 'Position', [30, 30, 140, 50]);

    % Option 0: No transient (constant 1.0)
    add_block('simulink/Sources/Constant', [sys '/No_Transient'], ...
        'Value', '1', 'Position', [30, 65, 100, 80]);

    % Option 1: Speed ramp (0.85 to 1.15 over 5s)
    % Ramp outputs slope*t after start. We add 0.85 bias.
    add_block('simulink/Sources/Ramp', [sys '/Speed_Ramp'], ...
        'Slope', '0.06', ...  % (1.15-0.85)/5 = 0.06
        'Start', '0', ...
        'Position', [30, 90, 110, 110]);
    add_block('simulink/Sources/Constant', [sys '/Ramp_Bias'], ...
        'Value', '0.85', 'Position', [30, 115, 90, 130]);
    add_block('simulink/Math Operations/Add', [sys '/Ramp_Add'], ...
        'Inputs', '++', 'Position', [130, 90, 160, 120]);
    add_line(sys, 'Speed_Ramp/1', 'Ramp_Add/1');
    add_line(sys, 'Ramp_Bias/1', 'Ramp_Add/2');
    add_block('simulink/Discontinuities/Saturation', [sys '/Ramp_Sat'], ...
        'UpperLimit', '1.15', 'LowerLimit', '0.85', ...
        'Position', [190, 90, 250, 115]);
    add_line(sys, 'Ramp_Add/1', 'Ramp_Sat/1');

    % Option 2: Load step (0.7 to 1.0 at t=2s)
    add_block('simulink/Sources/Step', [sys '/Load_Step'], ...
        'Time', '2', 'Before', '0.7', 'After', '1.0', ...
        'Position', [30, 120, 110, 140]);

    % Option 3: Thermal expansion (exponential rise 0.9 to 1.1)
    add_block('simulink/Sources/Step', [sys '/Thermal_Step'], ...
        'Time', '0', 'Before', '0', 'After', '1', ...
        'Position', [30, 155, 100, 175]);
    add_block('simulink/Continuous/Transfer Fcn', [sys '/Thermal_TF'], ...
        'Numerator', '[0.2]', 'Denominator', '[1.5 1]', ...
        'Position', [130, 155, 200, 175]);
    add_block('simulink/Math Operations/Add', [sys '/Thermal_Add'], ...
        'Inputs', '++', 'Position', [230, 155, 260, 185]);
    add_block('simulink/Sources/Constant', [sys '/Thermal_Base'], ...
        'Value', '0.9', 'Position', [150, 185, 210, 200]);
    add_line(sys, 'Thermal_Step/1', 'Thermal_TF/1');
    add_line(sys, 'Thermal_TF/1', 'Thermal_Add/1');
    add_line(sys, 'Thermal_Base/1', 'Thermal_Add/2');

    % Multiport switch (selects transient type)
    add_block('simulink/Signal Routing/Multiport Switch', ...
        [sys '/Trans_Switch'], ...
        'Inputs', '4', 'Position', [300, 50, 340, 180]);
    add_line(sys, 'Transient_Type/1', 'Trans_Switch/1');
    add_line(sys, 'No_Transient/1', 'Trans_Switch/2');
    add_line(sys, 'Ramp_Sat/1', 'Trans_Switch/3');
    add_line(sys, 'Load_Step/1', 'Trans_Switch/4');
    add_line(sys, 'Thermal_Add/1', 'Trans_Switch/5');

    % Multiply input signal by transient modulation
    add_block('simulink/Math Operations/Product', [sys '/Trans_Product'], ...
        'Position', [400, 110, 440, 155]);
    add_line(sys, 'sig_in/1', 'Trans_Product/1');
    add_line(sys, 'Trans_Switch/1', 'Trans_Product/2');

    % Output
    add_block('simulink/Ports & Subsystems/Out1', [sys '/trans_out'], ...
        'Position', [490, 125, 520, 140]);
    add_line(sys, 'Trans_Product/1', 'trans_out/1');
end

function wire_top_level(modelName)
    % Wire: Base_Signal → Signal_Sum (input 1)
    add_line(modelName, 'Base_Signal/1', 'Signal_Sum/1', ...
        'autorouting', 'smart');

    % Wire: Fault_Injection → Severity_Control → Transient → Signal_Sum (input 2)
    add_line(modelName, 'Fault_Injection/1', 'Severity_Control/1', ...
        'autorouting', 'smart');
    add_line(modelName, 'Severity_Control/1', 'Transient_Behavior/1', ...
        'autorouting', 'smart');
    add_line(modelName, 'Transient_Behavior/1', 'Signal_Sum/2', ...
        'autorouting', 'smart');

    % Wire: Noise_Model → Signal_Sum (input 3)
    add_line(modelName, 'Noise_Model/1', 'Signal_Sum/3', ...
        'autorouting', 'smart');

    % Add Quantizer block between Sum and outputs (quantization noise)
    add_block('simulink/Discontinuities/Quantizer', ...
        [modelName '/Quantizer'], ...
        'QuantizationInterval', '0.001', ...
        'Position', [950, 295, 990, 325]);

    % Re-wire: disconnect Sum→Scope and Sum→ToWorkspace, insert Quantizer
    delete_line(modelName, 'Signal_Sum/1', 'Scope/1');
    delete_line(modelName, 'Signal_Sum/1', 'To_Workspace/1');
    add_line(modelName, 'Signal_Sum/1', 'Quantizer/1', ...
        'autorouting', 'smart');
    add_line(modelName, 'Quantizer/1', 'Scope/1', ...
        'autorouting', 'smart');
    add_line(modelName, 'Quantizer/1', 'To_Workspace/1', ...
        'autorouting', 'smart');
end

%% ================================================================
%% HELPER FUNCTIONS
%% ================================================================

function delete_default_ports(sys)
    % Remove the default In1/Out1 blocks from a new Subsystem
    try delete_block([sys '/In1']);  catch, end
    try delete_block([sys '/Out1']); catch, end
    try delete_line(sys, 'In1/1', 'Out1/1'); catch, end
end

function add_goto_block(sys, name, tag, pos, srcPort)
    % Add a Goto block and optionally wire a source to it
    blkPath = [sys '/' name];
    add_block('simulink/Signal Routing/Goto', blkPath, ...
        'GotoTag', tag, ...
        'TagVisibility', 'global', ...
        'Position', pos);
    if nargin >= 5 && ~isempty(srcPort)
        add_line(sys, srcPort, [name '/1'], 'autorouting', 'smart');
    end
end

function add_from_block(sys, name, tag, pos)
    % Add a From block with specified tag
    blkPath = [sys '/' name];
    add_block('simulink/Signal Routing/From', blkPath, ...
        'GotoTag', tag, ...
        'Position', pos);
end

